import base64
import io

import requests
from PIL import Image

prompt = "A cat is running after a dog"
prompt = (
    "Prompt: A frozen split-second master shot capturing a high-velocity kinetic pursuit where a domestic feline is actively sprinting in pursuit of a domestic canine, rendered with an unprecedented level of microscopic detail, optical precision, and environmental complexity that exceeds 32K resolution clarity. The image should read as a single decisive moment—a cinematic still that implies both the instant before and the instant after—with every element serving the narrative of chase, scale inversion, and absurdist tension between predator and prey.\
THE FELINE PURSUER (BIOLOGICAL & KINETIC SPECIFICATIONS): The attacking entity is a mature male ginger mackerel tabby, weighing approximately 4.5 kilograms, exhibiting peak predatory physiological arousal. Its body is caught in the mid-air suspension phase of a full gallop, specifically the moment of 'gathered suspension' where all four paws are temporarily off the substrate, bunched beneath the torso before the explosive extension of the hind legs. The spinal column is flexed into a concave arch, storing potential energy in the longissimus dorsi muscles like a coiled spring. Every individual hair follicle on its pelt is rendered with distinct clarity, showing the complex banding pattern of pheomelanin (red/orange pigment) and eumelanin (dark brown stripes). The guard hairs on the dorsal ridge are raised in piloerection due to adrenaline flood, creating a spiky, electrified silhouette against the light. The undercoat is dense and downy, visibly ruffled by the turbulent air displacement caused by its own speed. Its facial expression is one of intense, focused aggression: ears are flattened backwards against the skull (the 'airplane ear' position) to minimize air resistance and protect them from potential debris, revealing the intricate cartilaginous structure and the fine inner ear fuzz. The eyes are wide open, exhibiting maximum pupillary dilation whereby the black pupils have swallowed almost the entire gold-green iris to take in maximum visual information, reflecting a distorted panorama of the street ahead on the curved cornea. The nictitating membrane (third eyelid) is fully retracted. The whiskers (vibrissae) on the muzzle are splayed far forward in a sensory net formation, vibrating slightly from wind resistance, while the supraorbital whiskers above the eyes are swept back. The jaw is slightly dropped, revealing the sharp, conical canines and the ridged hard palate; a small amount of saliva is present at the commissure of the lips, pulled backward by momentum. The front paws are extended forward, reaching for purchase, with the retractile claws partially unsheathed, showing the translucent keratin curve of the nails glinting in the sun. The paw pads are dark pink and leathery, showing minute cracks and calluses from wear.\
FELINE SUPPLEMENTARY ANATOMY & MOTION: The cat's tail is held low and slightly to the side, acting as a counterbalance; the tail fur is bristled, adding to the impression of aggression. The scapulae and humeri are visible beneath the skin during the stretch phase. The cat's thoracic cavity shows the rapid rise of respiration—the rib cage is expanded. Fine wrinkles of skin gather at the corners of the eyes (orbital skin) and at the bridge of the nose. The pinnae show the tragal notch and the helical fold with interior shadows. Individual toe beans on the extended forepaws are visible: four digital pads and one larger metacarpal pad per paw. The hind legs are coiled beneath the body, the gastrocnemius and tibialis anterior muscles taut. The cat's coat exhibits subtle variation: slightly paler fur on the belly and inner legs, darker stripes along the spine and flanks, and a faint M-shaped marking on the forehead typical of tabby patterning. Small scratches or old scars may be suggested on the nose or ear tips, implying a life of outdoor conflict.\
THE CANINE FUGITIVE (BIOLOGICAL & KINETIC SPECIFICATIONS): The fleeing entity is a massive, oversized Great Dane with a 'Harlequin' coat pattern (irregular black torn patches on a pure white background), weighing roughly 75 kilograms. It is in a state of abject terror and clumsy flight, caught in the extended suspension phase of a chaotic gallop. Its body is angled slightly diagonally as it attempts to look backward over its left shoulder at its tiny pursuer while simultaneously running forward, creating a torque in its spinal alignment. The dog’s massive jowls and loose facial skin are flapping wildly and asynchronously due to the centrifugal force and impact tremors of its gait, stretching like rubber sheets and exposing the pink, wet inner mucosal lining of the mouth and gums. Long ropes of viscous, translucent drool are flying from the corners of its mouth, suspended in mid-air in elongated globules, catching the light like glass beads, some strands already breaking into smaller droplets trailing behind it. Its enormous tongue is lolling out of the side of its mouth, whipped backward by the wind, showing the rough texture of the papillae and surface moisture. The dog’s eyes are rolling back in their sockets in a 'whale eye' expression of panic, showing a large crescent of white sclera lined with red capillaries, the brown irises frantically focused on the cat behind it. The large, floppy ears are thrown backward and inside out by the wind, exposing the complex, pale pink vascular network of the inner ear pinna, with sunlight passing through the thin tissue (subsurface scattering effect). Its massive paws, the size of dinner plates, are splayed wide for traction, kicking up a significant amount of debris. The rear right paw is currently making contact with the ground, showing the compression of the thick, rough digital pads and the metacarpal pad against the stone, shivering with the impact force.\
CANINE SUPPLEMENTARY ANATOMY & MOTION: The Harlequin pattern is irregular: one black patch covers the left eye and ear like a mask, another wraps the right haunch, and smaller spots dot the shoulders and back. The white areas show the pink skin beneath where the fur is thin. The dog's dewclaws are visible on the forelegs, and the nails are thick and blunt from pavement wear. The sternum and rib cage heave with panicked breathing; the xyphoid process may be suggested. Wrinkles cascade from the brow down the muzzle, each fold catching shadow and light. The dog's tail is tucked or held low in a submissive/fearful posture, the fur there also slightly raised. Saliva strands connect the tongue to the lips and to floating droplets, creating a web of moisture. The massive neck shows the trapezius and sternocephalicus muscles straining. One ear may be partially inverted while the other is fully blown back, adding to the asymmetry of panic. The black nose leather is wet and reflective; the philtrum is deep and shadowed.\
THE PHYSICS OF INTERACTION & ATMOSPHERE: The air between and around the subjects is thick with particulate matter generated by their passage. A turbulent wake of displaced air is visible as heat haze and subtle refractive distortions. Dust motes, pollen grains, fine silty soil particles, and fragments of dried leaves are suspended in a chaotic cloud, each particle catching the sunlight and creating a miniature flare. Where the dog’s paws impact the ground, there is an explosive radial burst of debris: small pebbles, grit, sand, and dust are ejected upwards in defined trajectories, some frozen sharp in the frame, others blurred by motion. A small, shallow puddle of dirty water has just been stepped in by the dog, creating a perfect crown splash of brown liquid, with individual droplets frozen in parabolic arcs, reflecting the sky. The sound of the scene is visually implied: the thud of heavy paws, the scrabbling of claws on stone, the panting of the dog.\
PHYSICS EXTENDED—PARTICULATES, WAKES & IMPACT: The cat's smaller mass displaces less material but its higher stride frequency kicks up a fine spray of grit in its wake. Vortex streets form briefly behind both animals before dissipating. The crown splash from the puddle shows a central column and a circular rim; droplets vary in size from mist to pea-sized, each with a highlight and a shadow. Pebbles in flight have distinct angular momentum; some rotate. Dust clouds diffuse light, creating a soft volumetric quality in the alley. Pollen and seeds (perhaps from the plane trees or roses) float in the mid-ground. The dog's exhalations might be suggested as a faint moisture cloud near its mouth. Scratches on the cobblestones from claws could be implied where the cat has previously touched down. The thermal distortion from the warm ground adds a slight shimmer to the lower portion of the frame.\
THE ENVIRONMENTAL MACRO-STRUCTURE: The chase takes place in a narrow, ancient cobblestone alleyway in a historic European town, perhaps somewhere in Tuscany or Provence, during late afternoon. The ground is paved with uneven, centuries-old granite and basalt cobblestones, worn smooth and rounded by time and traffic, showing a complex patina of mineral stains, lichen growth (circular patches of Xanthoria parietina and Physcia adscendens), and moss filling the deep, irregular cracks between the stones. Some stones are cracked or missing, replaced by packed earth. The architecture flanking the alley consists of two- and three-story medieval stone and stucco buildings. The walls are textured with peeling ochre and burnt sienna plaster, revealing rough-hewn stone blocks underneath. Ancient climbing roses (Rosa banksiae) and aggressive ivy (Hedera helix) cover large sections of the walls, their leaves detailed with veins, insect damage, and dust coatings. Wooden shutters, painted a faded, peeling cerulean blue, hang crookedly by rusted iron hinges next to windows with old, wavy glass panes that reflect the scene defensively. A rustic wooden door with heavy iron studs and a large, ornate knocker shows signs of advanced weathering, wood rot at the base, and layers of old varnish.\
ENVIRONMENTAL MACRO EXTENDED—ARCHITECTURE & MATERIALS: The alley width suggests two to three meters; the buildings lean slightly inward, narrowing the sky to a strip of blue. Stone blocks in the walls show tool marks—chisel and hammer—and occasional mason's marks or dates. Mortar between stones is recessed and darkened by age and moisture. Window boxes on upper floors hold more geraniums, basil, or rosemary; one has a small olive tree in a cracked pot. Downspouts of aged copper run green with patina; one is bent and drips a dark streak onto the wall. A narrow gutter runs along one side of the alley, half-clogged with leaves and debris. The cobblestones may show ruts from centuries of cart traffic. A single wrought-iron street lamp (gas-lamp style) stands against one wall, its glass dusty. The rooflines are terracotta tiles, some slipped or missing; chimneys rise with irregular brickwork.\
THE ENVIRONMENTAL MICRO-DETAILS: In the immediate foreground, out of focus, are the textures of the street: a discarded, crushed aluminum can of a vintage Italian soda brand, a crumpled cigarette butt, fallen plane tree leaves in various states of decay showing skeletal vein structures. In the mid-ground, a startled flock of feral pigeons (Columba livia) is taking flight in a chaotic explosion of feathers; their wings are blurred with motion, but individual feathers are visible, showing iridescence on their necks. A small terracotta pot filled with red geraniums has been knocked over by the dog, shattering on the stones, spilling dark, rich potting soil, root balls, and broken terracotta shards across the path. In the deep background, the alley curves, leading the eye to a sunlit town square with a fountain and a few blurred human figures reacting to the commotion. The air is warm and dusty.\
ENVIRONMENTAL MICRO EXTENDED—FOREGROUND TO BACKGROUND: Foreground: the soda can shows a faded logo and a dent; the cigarette has a lipstick mark. Ants may be suggested near a dropped crumb or piece of fruit. A cracked olive pit, a twist of paper, a lost key or coin. Mid-ground: individual pigeons show wing bars and tail bands; one has a metal ring on its leg. The geranium blossoms are a deep red (Pelargonium); leaves are rounded and slightly succulent. Soil spills in a fan; a single earthworm might be visible. A bicycle leans against the wall, one wheel bent. A cat-sized shadow or a second cat watching from a windowsill could add narrative depth. Background: the fountain has a classical figure (nymph or dolphin); water is a soft blur. Human figures are in period or contemporary casual dress, one pointing, one with hands on hips. A café awning, a market stall, a Vespa parked near the square. The sky is a gradient from warm white near the horizon to deeper blue above, with no clouds or one or two small cumulus.\
LIGHTING, OPTICS, AND CINEMATOGRAPHY: The scene is illuminated by the dramatic, warm light of the \"Golden Hour\" sun, positioned low in the west at approximately a 25-degree angle. The light source is intense and directional, casting extremely long, deep shadows that stretch down the alleyway, defining the topography of the cobblestones and the musculature of the animals. The color temperature is a warm 3500K. The lighting creates strong rim lighting (backlighting) on both animals, making their fur glow like halos and highlighting the translucent quality of the dog's drool and ears. The shot is captured on a large-format cinema camera (akin to an ARRI Alexa 65 or IMAX film stock) using a prime 35mm lens at a wide aperture of f/1.4. This results in an incredibly shallow depth of field; the sharpest focus is locked precisely on the cat’s determined eyes and the dog’s panicked backward glance. The foreground and background dissolve into a creamy, complex bokeh of light circles and soft shapes. The shutter speed is extremely fast, at least 1/8000th of a second, to freeze every element of the chaotic motion with absolute crystalline sharpness, eliminating almost all motion blur except for the fastest-moving tips of wings and tails, creating a hyper-real sensation of time standing still. The color grading is cinematic and rich, with deep, crushed blacks in the shadows retaining detail, saturated warm tones in the highlights, and a slight film grain texture across the entire image to enhance the organic feel. Lens flare is present but controlled, a subtle warm streak from the low sun hitting the lens elements. The overall composition is dynamic and chaotic, capturing the raw, humorous, and intense energy of the chase.\
LIGHTING AND OPTICS EXTENDED: Secondary fill light is minimal, perhaps from sky bounce in the upper alley, preventing the shadows from going to pure black and retaining detail in the fur and stone. The rim light on the cat's dorsal hairs creates a thin bright line; on the dog, it outlines the ear and the drool strands. Chromatic aberration may be subtly present at the frame edges—a faint green/magenta fringe on high-contrast edges—adding lens character. Bokeh balls from out-of-focus highlights (windows, wet surfaces) are circular or slightly cat's-eye due to the wide aperture. The film grain is fine, ISO-equivalent low (e.g. 200–400), with no visible noise in the shadows. The aspect ratio could be implied as 2.39:1 anamorphic or 1.85:1. Vignetting is very slight or absent. The composition follows a diagonal thrust from lower-left (cat) to upper-right (dog), with the alley lines reinforcing depth. The rule of thirds places the main conflict near the intersections. Negative space in the sky and in the soft foreground balances the chaos of the central action.\
"
)

response = requests.post(
    "http://localhost:40021/v1/images/generations",
    json={
        "prompt": prompt,
        # "prompt": "a horse jumping over a fence nearby a babbling brook",
        "size": "1024x1024",
        "num_inference_steps": 50,
        "seed": 42,
    },
)

# Check response and decode
resp_json = response.json()
if response.status_code != 200:
    print(f"Error: HTTP {response.status_code}")
    print(resp_json)
elif "error" in resp_json:
    print(f"API Error: {resp_json['error']}")
elif "data" not in resp_json:
    print(f"Unexpected response format: {resp_json}")
else:
    img_data = resp_json["data"][0]["b64_json"]
    img_bytes = base64.b64decode(img_data)
    img = Image.open(io.BytesIO(img_bytes))
    img.save("cat.png")
    print("Image saved to cat.png")
